### ISSUE TITLE
Community analyzers project

### ISSUE THREAD

**Issue by nojaf** [ionide/FSharp.Analyzers.SDK#133]
Would it make sense to have a community project with analyzers in this repository?
It should be a set of generic analyzers generally conceived as best practices when writing F# code.

Some motivations to have this:
- Writing your analyzer, packaging it, shipping it and consuming it might be a too big step for most people. If there were a safe community space where an individual analyzer could be contributed, it would lower the threshold.
- We could have a `nightly` branch and use preview FCS releases to identify breaking changes quite early.
- It would also allow us to test these analyzers every time someone contributes to the SDK.
- I believe this would be insightful to see what building blocks are missing right now. 

Some downsides:
- This might bring us into some discussion territory on whether proposals are generic enough.
- Changing the SDK would mean fixing a bunch of analyzers.
- The barrier to contributing an analyzer would still somewhat high. To save ourselves some trouble, the minimum requirements would be to have: an analyzer, a well-covering test suite and a documentation page entry.
- The same folks would need to maintain it.

**Comment by Numpsy** [comment]
A general question on different code analysis / linting approaches after the presentation last week:

I've tried running FSharpLint on a few small projects, and it's found a few things worth changing, but I've also fallen over a few bugs in it.

The thing there is, the code base over there is a bit out of date with tooling and such (e.g. it's .NET 5.0, using a somewhat old version of FCS etc), so it feels like it needs a bit of work before even getting to fixes.

so the question is, in the grand scheme of things - how much is it worth spending time on that, vs. trying to build analyzers that do the same rules? (also refs https://github.com/fsharp/FsAutoComplete/issues/942 as trying to have separate integrations with both FSharpLint and Analyzers sounds like a bunch of duplicated effort to me?).

Note: I know very little about the implementation details and am looking at it just out of interest at the moment, so it's really just a question of what direction things might be heading in

**Comment by nojaf** [comment]
I believe it's important to weigh the pros and cons of contributing to both FSharpLint and the analyzer SDK.

FSharpLint is a more mature project, and in the short term, your contributions there could have a more immediate impact. If you're interested in general linting, FSharpLint might be the better choice. However, if you have a specific case or rule you want to implement, FSharpLint could still work if it benefits others, but you'll need approval from the maintainers.

On the other hand, the analyzer SDK allows you to create your custom rule. This flexibility is a significant advantage. Analyzers have the advantage of accessing the typed tree, which FSharpLint lacks (I think). So, depending on your specific goals, you should consider the right tool for the job.

I hope this provides some clarity.

**Comment by Krzysztof-Cieslak** [comment]
One of the main reasons why I've created Analyzers in first place were certain limitations of FSharpLint - such as lack of access to typed tree.
And don't get me wrong, I think FSharpLint is an important project for the F# ecosystem, and it fulfils its goals well, but Analyzers give us options to create more advanced, specific types of rules that FSharpLint can't handle. As such, I believe both those projects can be used together where FSharpLint provides more "stylistic" lints, while Analyzers can provide "semantic" analyzers.

**Comment by nojaf** [comment]
Tracking in https://github.com/ionide/ionide-analyzers
