### ISSUE TITLE
What's an analyzer?

### ISSUE THREAD

**Issue by jrr** [ionide/FSharp.Analyzers.SDK#14]
I arrived here from [F# weekly](https://sergeytihon.com/2020/02/22/f-weekly-8-2020-fsharp-analyzers-sdk/) and am trying to understand more about this project. Clearly it's for building analyzers. What's an analyzer? ;)

Are they like [roslyn analyzers](https://docs.microsoft.com/en-us/visualstudio/code-quality/roslyn-analyzers-overview?view=vs-2019) for F#?

How do you use one? Did they exist before FSharp.Analyzers.SDK came along?

Say I have an idea for a new squiggle in my F# projects, and I manage to build a custom analyzer. How do I use that analyzer in my F# project?

Can you run them with a command-line tool? (e.g. `dotnet analyze-fs MyCustomAnalyzer my-project.fsproj`)

Sorry for the barrage of questions! Hopefully some improvement to the readme attracts more users and contributors.

**Comment by baronfel** [comment]
Taking this point by point:

1. yep! Taking a bit from the [README](https://github.com/ionide/FSharp.Analyzers.SDK#writing-analyzers): 
> These class libraries expose a value of type `Analyzer` which is effectively a function that has input of type `Context` and returns a list of `Message records.
> ...
> The input `Context` is a record that contains information about a single F# file such as the typed AST, the AST, the file content, the file name and more. The SDK runs this function against all files of a project during editing. The output messages that come out of the function are eventually used by Ionide to highlight the inspected code as a warning or error depending on the Severity level of each message.

2. This needs to be added to the README in this repo, but [Npgsql.FSharp.Analzyer](https://github.com/Zaid-Ajaj/Npgsql.FSharp.Analyzer#using-the-analyzer) has great instructions we could use as a base. The short form is you install the analyzer via nuget/paket and add a config setting to Ionide to tell it where to look for analyzers. In the future this mechanism might change to be more convention-based?

3. See point 2 for the technical side. You'd publish the package, reference that in your project, and add the Ionide setting as described.

4. Yes! This SDK also includes a command-line dotnet SDK tool named `fsharp-analzyers`, so you can install it as a local tool in your projects (`dotnet tool install fsharp-analyzers`) and run it like `dotnet fsharp-analyzers --project <path to project> --analyzers-path <path to analyzer dir>`.

**Comment by Krzysztof-Cieslak** [comment]
I've also written the article about F# analyzers when I've introduced them initially - https://medium.com/lambda-factory/introducing-f-analyzers-772487889429
