### ISSUE TITLE
Bump framework target to netcoreapp3.1

### ISSUE THREAD

**Issue by aaronpowell** [ionide/FSharp.Analyzers.SDK#17]
At present there's a restriction that the analyser much target `netcoreapp2.0` whereas the latest is `netcoreapp3.1`.

Is there a reason that this restriction can't be loosened? I've hit a problem where I want to use FSharp.Control.AsyncSeq to convert `IAsynEnumerable` to `AsyncSeq` but that's only available in the `netstandard2.1` package, which matches `netcoreapp3.1`, so I can't take a dependency on it.

**Comment by baronfel** [comment]
The big blocker for this (as far as I understand it), is that because the analyzer is loaded in-process in FSAutoComplete (and potentially other runtimes) the analyzers loaded are limited to the runtimes supported by FSAC, which in this case is netcoreapp2.1 at best.

**Comment by aaronpowell** [comment]
Yeah I figured it's going to be a dependency of a dependency of a dependency that's the cause, but it can't hurt to ask 😉

**Comment by baronfel** [comment]
if it's any consolation, Ionide 5.0 is wanting to bump to netcoreapp3.1 (https://github.com/ionide/ionide-vscode-fsharp/issues/1305) which would unblock this.

**Comment by aaronpowell** [comment]
Ah cool, I haven't been following the Ionide v5 stuff.

**Comment by Krzysztof-Cieslak** [comment]
Analyzer SDK now targets `net5.0`
