### ISSUE TITLE
Add a SDK.Tests package

### ISSUE THREAD

**Issue by TheAngryByrd** [ionide/FSharp.Analyzers.SDK#18]
**Is your feature request related to a problem? Please describe.**
With the growing number of analyzers, writing tests for it becomes fairly tricky.  I came up with loading files/projects via my [analyzers](https://github.com/BinaryDefense/BinaryDefense.FSharp.Analyzers/blob/master/tests/BinaryDefense.FSharp.Analyzers.Tests/Analyzer.fs) loader that copies most of the loading logic from the [CLI project](https://github.com/ionide/FSharp.Analyzers.SDK/blob/master/src/FSharp.Analyzers.Cli/Program.fs#L56). This could get out of sync with the main repo.

**Describe the solution you'd like**

I think we should provide a package for analyzer authors to consume in their test projects to keep loading consistent. This would involve publishing the `ProjectSystem`, as listed in https://github.com/fsharp/FsAutoComplete/issues/564

**Describe alternatives you've considered**

Potentially splitting it into a file and consume it via paket's github dependencies.

**Additional context**

**Comment by cmeeren** [comment]
Would like this! The only thing I have to go on right now are analyzer bootstraps in existing projects like [this](https://github.com/Zaid-Ajaj/Npgsql.FSharp.Analyzer/blob/798ab4fe989690688d61ed1196ca79bb4e1aca37/tests/NpgsqlFSharpAnalyzer.Tests/Analyzer.fs), [this](https://github.com/aaronpowell/FSharp.CosmosDb/blob/8d1cb92d294d56686ffa50eca56f123cf209eb96/tests/FSharp.CosmosDb.Analyzer.Tests/AnalyzerBootstrap.fs), or [this](https://github.com/BinaryDefense/BinaryDefense.FSharp.Analyzers/blob/f9c5393df188ca75d22da7b4db0f81cc01e9d562/tests/BinaryDefense.FSharp.Analyzers.Tests/Analyzer.fs), which contains a lot of unexplained stuff.

**Comment by cmeeren** [comment]
In Flinter, I have, for the time being, implemented analyzer bootstrap like [this](https://github.com/cmeeren/Flinter/blob/main/src/Flinter.Tests/AnalyzerBootstrap.fs) ([permalink to current version](https://github.com/cmeeren/Flinter/blob/d3db5b7968bae60fdb48f25b4111c49b654399dd/src/Flinter.Tests/AnalyzerBootstrap.fs)).

In addition to analyzer bootstrap, it would be great to have simple test/assertion helpers. After having long used Expecto and Unquote but not been very happy with either (e.g. when it comes to assertion failure messages), I have experimented with (and fallen in love with) xUnit + [Fluent Assertions](https://fluentassertions.com/), and have created [some helpers](https://github.com/cmeeren/Flinter/blob/main/src/Flinter.Tests/Assertions.fs) ([permalink to current version](https://github.com/cmeeren/Flinter/blob/d3db5b7968bae60fdb48f25b4111c49b654399dd/src/Flinter.Tests/Assertions.fs)) that allows writing code like this, allowing you to assert (with no boilerplate) the existence/position of messages, and arbitrary content in the messages.

```f#
[<Fact>]
let ``Returns correct message data for an invalid parameter`` () =
    """
    let f a Foo c = 0
            ^^^
    """
        .Should()
        .ContainOnlyMarkedErrors(analyze)
        .And
        .MatchRespectively(
            Msg(
                message = "The parameter name 'Foo' does not follow the rule for parameter names.",
                code = "FLN0000",
                type' = "FunctionParameterNaming"
            )
        )

[<Fact>]
let ``Handles multiple invalid parameter names in multiple top-level functions`` () =
    """
    let f1 a Foo BAR = 0
             ^^^ ^^^
    let f2 a b c = 0
    let f3 Baz b c = 0
           ^^^
    """
        .Should()
        .ContainOnlyMarkedErrors(analyze)
```

**Comment by TheAngryByrd** [comment]
Gonna close this since https://github.com/ionide/FSharp.Analyzers.SDK/pull/95 is done. Other issues can track more specific work.
