### ISSUE TITLE
Console colour not being reset before fsharp-analyzers cli tool exits?

### ISSUE THREAD

**Issue by Numpsy** [ionide/FSharp.Analyzers.SDK#215]
When testing #214 I got this in my console (Windows 10 with windows terminal):

![image](https://github.com/user-attachments/assets/0382cba0-4b8d-479e-8dd1-fc42f73b761d)

i.e. it printed the analyzer suggestion in blue, and then left the console colour set to blue such that the next prompt was blue.

I wonder whether https://github.com/ionide/FSharp.Analyzers.SDK/blob/bee7ea7a44b20b09d594dc9e23b407b1f1d086f6/src/FSharp.Analyzers.Cli/CustomLogging.fs#L75 should be writing out the escape codes to reset the colour rather than just setting Console.ForegroundColor ?

Maybe it'd also be fixed by #180 though, I haven't tested it.

**Comment by dawedawe** [comment]
Hey @Numpsy,
thanks for making us aware of this. I'll try to take a look at the end of the week.
