### ISSUE TITLE
Rename to FSharp.Analysers.SDK ?

### ISSUE THREAD

**Issue by Thorium** [ionide/FSharp.Analyzers.SDK#24]
**Describe the bug**
A possible spelling mistake in the product name.

**To Reproduce**
Install en-UK language pack, and spell-check the project name.

**Expected behaviour**
No red line should appear.

**Comment by forki** [comment]
Troll ;-)

Tuomas Hietanen <notifications@github.com> schrieb am Sa., 6. Juni 2020,
11:23:

**Comment by Thorium** [comment]
A bit political maybe.
