### ISSUE TITLE
Update to net5

### ISSUE THREAD

**Issue by tforkmann** [ionide/FSharp.Analyzers.SDK#29]
Hi there,

I would like to update the FSharp.Analyzers.SDK to .net5.0 bc I'm working on a AzureTackle.Analyzer.

While updating I ran into following issue:

The loadProject helper is not working anymore bc the fsautocomplete got updated.

Any idea how to load project with the new FSAutocomplete?
FSharp.Analyzers.SDK
![image](https://user-images.githubusercontent.com/4168951/102588061-1d7c5580-410d-11eb-8b10-3f25f2e14cf2.png)

Thanks in advance!

**Comment by baronfel** [comment]
This is in a bit of an odd state until https://github.com/fsharp/FsAutoComplete/pull/673 lands.

That MR removes the project system from FSAC and pushes it to a new nuget package, at which point this repo could just depend on that package and drop the FSAC dependency entirely.

**Comment by tforkmann** [comment]
Ahh ok! Thanks for the info!
Trying to find a workaround for now.

Thx

**Comment by baronfel** [comment]
The most future-proof way to go at this minute would be to:

* replace the paket github reference on `fsharp/FSAutoComplete` to one for `ionide/dotnet-proj-info` at the `rewrite` branch: https://github.com/ionide/dotnet-proj-info/tree/rewrite
* replace usages of `ProjectSystem` with matching/new members from `Dotnet.ProjInfo.ProjectSystem`: https://github.com/ionide/dotnet-proj-info/tree/rewrite/src/Dotnet.ProjInfo.ProjectSystem

You should be able to find the matching members pretty easily, but you can refer to the FSAC MR I linked for the details of how FSAC itself moved to this new library.

**Comment by tforkmann** [comment]
Sweet will try that! Thx

**Comment by tforkmann** [comment]
@baronfel Going to use the new Ionide.ProjInfo package. Good timing :D

**Comment by Krzysztof-Cieslak** [comment]
Hey, yes, I've just pushed the new packages.

**Comment by tforkmann** [comment]
Closed with #30
