### ISSUE TITLE
Can analyzers be run as a dotnet tool?

### ISSUE THREAD

**Issue by cmeeren** [ionide/FSharp.Analyzers.SDK#45]
If I create an analyzer using this SDK, can it automatically be run using a dotnet tool? Or does this tool only provide integration with Ionide, and everything else (including running through a CLI) I will need to implement myself?

**Comment by TheAngryByrd** [comment]
Yep analyzers can be run from the dotnet-tool. 

See [miniscaffold](https://github.com/TheAngryByrd/MiniScaffold/blob/c77b76bfba47b74e10774a7c3be61c6aa395d4f5/Content/Library/build/build.fs#L401) template using the tool.

**Comment by cmeeren** [comment]
Thanks!
