### ISSUE TITLE
Modernize/simplify tooling/CI/packaging?

### ISSUE THREAD

**Issue by cmeeren** [ionide/FSharp.Analyzers.SDK#49]
As may be evident from recent issues and comments, I'd like to help out in the development if FSharp.Analyzers.SDK. In that light, I am wondering if you are open to changes that I think would make it simpler to contribute and make at least me feel more at home. 

I am willing to make any or all of these changes myself through PRs.

In short, I would like to be able to open the solution in VS/Rider/VSCode and have it "just work" using standard .NET tooling, which is really good nowadays (better than some years ago). Moreover, I would like to not have the additional complexity of Fake and Paket to think about.

These suggestions are based on several years of experience with several other F# OSS packages I have created and maintain, as well as tens of F# projects at work.

I realize these may be controversial suggestions and fully expect to be turned down, but given the lack of activity in this repo (last commit over 8 months ago), the current maintainers may want to lower the barrier of entry for contibutions or even bring on additional maintainers, so I'd like to ask anyway.

* Use NuGet (with lock files) instead of Paket. I see no compelling reason to use Paket now that NuGet has become so good in recent years, with support for lock files. NuGet is more compatible with stock tooling (e.g. VS), and is the "default" for the .NET ecosystem.
* Remove Fake, unless it does something that is difficult to accomplish otherwise. When it comes to packaging and releasing, I have yet to experience problems with stock GitHub and `dotnet` CLI functionality, assembly/package information in project files, etc. For releases, I keep a manually curated `RELEASE_NOTES.md` and have always found this more than adequate, and if I need more documentation than fits in the readme, I have used a separate easily searchable `DOCUMENTATION.md` file like [Giraffe does](https://github.com/giraffe-fsharp/Giraffe/blob/master/DOCUMENTATION.md).
* Install Fantomas as a dotnet tool and reformat the code, then enforce code style during CI. I do this in Flinter with [this config](https://github.com/cmeeren/Flinter/blob/e08899d4903f2d75c431d37eb71b27d157bc9e70/.editorconfig), which is basically the standard except Stroustrup brackets are enabled (which I find gives more readable code that is easier to edit and has less line damage in diffs).
* Build on GitHub. Why use an external service when everything you need is right here? (I realize that may not have been the case when the project was set up, of course.)
* Set up a `Directory.Build.props` that looks like [this](https://github.com/cmeeren/Flinter/blob/e08899d4903f2d75c431d37eb71b27d157bc9e70/Directory.Build.props). It uses DotNet.ReproducibleBuilds, enables warnings as errors, and warns (errors) on unused values.
* Add a strict `global.json` to ensure repeatable builds (minor versions should be compatible, but bugs in FSharp.Core packaging have broken my builds even on minor updates to dotnet tooling on build agents)
* Add `nuget.config` to ensure repeatable builds
* Probably some other stuff, too; I haven't looked too closely at all the files.

**Comment by baronfel** [comment]
Definitely on board with all of that - inertia is the only reason this repo uses what it currently uses.

The only caveat I'd add is that eventually, _hopefully_, this repo is sunsetted in favor of https://github.com/fsharp/fslang-design/blob/main/tooling/FST-1033-analyzers.md. So humongous investments in tooling might not worthwhile. Everything you listed above is a good idea to do, though!

**Comment by cmeeren** [comment]
Great! I'll take that as a cue to start submitting PRs. The changes shouldn't be massive.

I think I'll start with adding GitHub actions and removing Fake, since otherwise, some of the other changes would require updating the Fake build script.

**Comment by cmeeren** [comment]
Currently, the project won't even build from scratch on my system.

Due to how the current tooling (CI, Fake, Paket, etc.) is fairly intermingled, it's hard to separate out one and one change. Especially when I can't even build from scratch with the current tooling - then I'd be flying blind.

Are you open for a more messy PR that does everything at once? (Except Fantomas and formatting, that is a cleanly separated change that will come later.)

**Comment by baronfel** [comment]
Fire away!

**Comment by cmeeren** [comment]
Wonderful.
