### ISSUE TITLE
Surface FSharpCheckFileResults in Context

### ISSUE THREAD

**Issue by cmeeren** [ionide/FSharp.Analyzers.SDK#67]
The `Context` type surfaces several fields that are based on `FSharpCheckFileResults`, but not `FSharpCheckFileResults` itself. This type has several useful methods, such as `GetSymbolUseAtLocation`, that should be available to analyzers. I therefore propose surfacing this type in `Context`.

**Comment by TheAngryByrd** [comment]
Done in https://github.com/ionide/FSharp.Analyzers.SDK/pull/73
