### ISSUE TITLE
Add a `-p` flag to allow passing MSBuild properties through to the MSBuild evaluation portion of checking.

### ISSUE THREAD

**Issue by baronfel** [ionide/FSharp.Analyzers.SDK#84]
**Is your feature request related to a problem? Please describe.**

MSBuild/.NET CLI flags often change behavior - notably flags like `-c`, `-r`, `--arch`, `--os`, and `-p`. At minimum we need to allow for MSBuild properties to be passed in to allow for checking of AST shapes/compiler defines that actually match what the .NET CLI will compile against.

**Describe the solution you'd like**

Minimum:
* -p|--property flag that can be applied multiple times and accepts MSBuild properties. These are key=value pairs.

Bonus - parity with the .NET CLI:
* -r|--runtime flag for passing through the RuntimeIdentifier MSBuild property
* --arch flag for inferring the OS portion of the RID only and explicitly specifying the architecture part
* --os flag for inferring the architecture portion of the RID only and explicitly specifying the OS part
* -c flag for passing through the Configuration MSBuild property

**Comment by dawedawe** [comment]
I think so.
@baronfel are you still missing something?

**Comment by baronfel** [comment]
Nope, we should be all good to go here :)
